name: {{project_name.snakeCase()}}
description: {{project_name.titleCase()}} package.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  {{#in_project}}flutter:
    sdk: flutter
  dependencies:
    path: ../../core/dependencies{{/in_project}}{{^in_project}}equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0{{/in_project}}

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
