name: {{project_name.snakeCase()}}
description: "{{project_description}}"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  get_it: ^9.2.0
  injectable: ^2.5.1
  json_annotation: ^4.9.0

dev_dependencies:
  alchemist: ^0.13.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
