name: dependencies
description: Export 3rd party and core dependencies.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  components:
    path: ../components
  di:
    path: ../di
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_test:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^6.0.1
  internationalization:
    path: ../internationalization
  mocktail: ^0.3.0
  network:
    path: ../network
  routes:
    path: ../routes
  theme:
    path: ../theme
  very_good_analysis: ^3.1.0
