name: dependencies
description: Export 3rd party and core dependencies.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  components:
    path: ../components
  di:
    path: ../di
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  internationalization:
    path: ../internationalization
  network:
    path: ../network
  theme:
    path: ../theme

dev_dependencies:
  flutter_test:
    sdk: flutter
